- id: doi:10.7717/peerj.5461
  image: images/papers/peerj_cranberry.png
  tags:
    - cranberry
    - image analysis
    - genetic mapping


- id: doi:10.1016/j.pbi.2021.102150
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1369526621001515-gr1_lrg.jpg
  tags:
    - phenomics
    - phenomic selection
